[build-system]
requires = [
    "setuptools>=45",
    "wheel",
    "cython",
    "scikit-build>=0.12",
    "cmake",
    "setuptools_scm>=6.2"
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
testpaths = "tests"
timeout = "120"
